name: Java Maven Library Publisher
# Based on "Mathieu Soysal (@MathieuSoysal)"

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK for deploy to OSSRH
        uses: actions/setup-java@v3.13.0
        with:
          distribution: "zulu"
          java-version: 21
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Build with Maven and Publish Modules
        run: |
          for module in $(find . -name "pom.xml" -not -path "./target/*"); do
            module_dir=$(dirname $module)
            echo "Building and publishing module in $module_dir"
            cd $module_dir
            mvn -B deploy -PossrhDeploy
            cd -
          done

      - name: Prepare Maven environment with Java for deployment to OSSRH
        run: export MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED"
        shell: bash
