name: Java Maven Library Publisher
# Based on "Mathieu Soysal (@MathieuSoysal)"

on:
  release:
    types: [ created ]
  workflow_dispatch:

env:
  MAVEN_ARGS: --no-transfer-progress
  NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
  NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS: --no-transfer-progress
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK for deploy to MVN Central
        uses: actions/setup-java@v3.13.0
        with:
          distribution: "zulu"
          java-version: 17
          server-id: central
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set up Maven settings.xml
        uses: ./.github/create-settings-xml
        with:
          nexus_username: ${{env.NEXUS_USERNAME}}
          nexus_password: ${{env.NEXUS_PASSWORD}}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to Apache Maven Central
        run: mvn deploy -PcentralDeploy
        shell: bash
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}